### get all users

GET {{port6012}}/user/all HTTP/1.1


### create user (client)

POST {{port6012}}/user/create HTTP/1.1
Content-Type: application/json

{
  "email": "said@mailto.plus",
  "fcmToken": "fcm1",
  "fullname": "Said Bin A. Rahman",
  "password": "Aw32@320",
  "role": "CLIENT"
}


### create user (seller)

POST {{port6012}}/user/create HTTP/1.1
Content-Type: application/json

{
  "email": "said@mailto.plus",
  "fcmToken": "fcm1",
  "fullname": "Said Bin A. Rahman",
  "password": "Aw32@320",
  "role": "CLIENT"
}


### verify user

POST {{port6012}}/user/verify HTTP/1.1
Content-Type: application/json

{
  "otp": "790548",
  "userId": "0974374e-b51f-438d-ac10-7abc7c3ad3f7"
}
